---
title: Applied Generalized Linear (Mixed) Modelling
author: "Benedikt Ehinger"
date: "March 19th, 2018"
format:
  revealjs:
    incremental: false
    widescreen: false
    css: custom.css
    theme: "simple"
    transition: "slide"
    slide-number: true
    
execute:
  cache: true
engine: julia
---
## bla

```{julia}
1+2
```
```{julia}
#| echo: false
using CairoMakie, AlgebraOfGraphics, SwarmMakie
using DataFrames, DataFramesMeta
using GLM, MixedModels, Distributions
using LinearAlgebra, Random, StatsBase

# CairoMakie is the backend for AlgebraOfGraphics
CairoMakie.activate!()

# Global theme settings
set_theme!(Theme(
    fontsize = 25,
    font = "Helvetica",
))

# Helper: make swarm (beeswarm) points along x-axis
function swarm_along_x!(ax, x; y_pos=-1, swarm_width=0.5)
    xs = similar(x)
    for i in eachindex(x)
        xs[i] = x[i] + (rand() - 0.5) * swarm_width
    end
    scatter!(ax, xs, fill(y_pos, length(xs)), markersize=6, alpha=0.7)
    return ax
end

# More Reveal options in the bottom
nothing;
```
```{julia}
plot([1,2,3,4])
```





# Overview
- Warmup
- Why statistics
- do it yourself statistics
    - **three important concepts**
    - there is only one statistical test
- Linear Regression
- Multiple Regression
- Categorical Variables
- Interactions and the famous 2x2 design
- Inference
- Asumptions
- Bootstrapping
- Four ways of statistics
- Equivalence of traditional tests




## Three extremely important concepts

 - Population
 - Sample
 - Sampling Distribution

<aside class="notes">
These concepts are very important to understand frequentist statistics
</aside>

```{julia}
Random.seed!(1)
data_sim = DataFrame(height = randn(70000) .* 10 .+ 170)

f = Figure(size=(500, 400))
ax = Axis(f[1,1], xlabel="", ylabel="")
hist!(ax, data_sim.height, bins=50, colormap=:virido)
xlims!(ax, (120, 220))
f
```


## Population

```{julia}
Random.seed!(1)
data_sim = DataFrame(height = randn(50) .* 10 .+ 170)

f = Figure(size=(500, 400))
ax = Axis(f[1,1], xlabel="", ylabel="")
hist!(ax, data_sim.height, bins=40, colormap=:virido)
xlims!(ax, (120, 220))
swarm_along_x!(ax, data_sim.height; y_pos=-0.1)
f

```


```{julia}
Random.seed!(1)
data_sim = DataFrame(height = randn(70000) .* 10 .+ 170)

f = Figure(size=(500, 400))
ax = Axis(f[1,1], xlabel="", ylabel="")
hist!(ax, data_sim.height, bins=50, colormap=:virido)
xlims!(ax, (120, 220))
f
```

This could be the height of the **population** of **all** people in the world. The left example is a sub-population (or a sample).


<aside class="notes">
We are usually interested in the population of all humans. In order that statistical inference (according to Fisher) works, we do need to assume that the population is infite. The reason is, that else draws from the population that are not infinite are dependent on each other [source](https://www.repository.utl.pt/bitstream/10400.5/2327/1/wp022008.pdf). E.g. you have a population of five mice, two white and three black. If you sample three mice and all of them are black, you now know that the other mice are white. If the population would be infinite, you would not have that problem. This is more a minor detail, something to think about.

</aside>